- name: install nginx
  hosts: Elastic_Master01
  become: yes
  tasks:
    - name: update
      apt: update_cache=yes    
    - name: Install Nginx
      apt: name=nginx state=latest
      notify:
        - restart nginx
